services:
  postgresql:
    image: postgres:13.7-alpine
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=shareit
      - POSTGRES_PASSWORD=shareit

  shareit-server:
    build: server/
    ports:
      - "8081:8081"
    depends_on:
      - postgresql
    environment:
      - DB_NAME=shareit
      - POSTGRES_USER=shareit
      - POSTGRES_PASSWORD=shareit
      - DB_HOST=postgresql
      - DB_PORT=5432
      - SHARE_IT_SERVER_PORT=8081

  shareit-gateway:
    build: gateway/
    ports:
      - "8080:8080"
    depends_on:
      - shareit-server
    environment:
      - SHARE_IT_GATEWAY_PORT=8080
      - SHARE_IT_SERVER_HOST=shareit-server
      - SHARE_IT_SERVER_PORT=8081