DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS items CASCADE;
DROP TABLE IF EXISTS booking_statuses CASCADE;
DROP TABLE IF EXISTS bookings;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS requests;

CREATE TABLE users (
    user_id int GENERATED BY DEFAULT AS IDENTITY,
    user_name varchar(200) NOT NULL,
    email varchar(200) NOT NULL,

    CONSTRAINT pkey_user PRIMARY KEY(user_id),
    CONSTRAINT uq_user_name UNIQUE(user_name),
    CONSTRAINT uq_user_email UNIQUE(email)
);


CREATE TABLE requests (
    request_id int GENERATED BY DEFAULT AS IDENTITY,
    description varchar(250) NOT NULL,
    user_id int NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL,

    CONSTRAINT pkey_request PRIMARY KEY(request_id),
    CONSTRAINT fkey_request_user FOREIGN KEY(user_id)
        REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TABLE items (
    item_id int GENERATED BY DEFAULT AS IDENTITY,
    user_id int NOT NULL,
    item_name varchar(200) NOT NULL,
    description varchar(200) NOT NULL,
    available boolean NOT NULL,
    request_id int,

    CONSTRAINT pkey_item PRIMARY KEY(item_id),
    CONSTRAINT fkey_item_user FOREIGN KEY(user_id)
        REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT fkey_item_request FOREIGN KEY(request_id)
        REFERENCES requests(request_id)
);

CREATE TABLE booking_statuses (
    booking_status_id int GENERATED BY DEFAULT AS IDENTITY,
    booking_status_name varchar(50) NOT NULL,

    CONSTRAINT pkey_booking_status PRIMARY KEY(booking_status_id)
);

INSERT INTO booking_statuses (booking_status_name)
VALUES ('WAITING'),
       ('APPROVED'),
       ('REJECTED'),
       ('CANCELED');

CREATE TABLE bookings (
    booking_id int GENERATED BY DEFAULT AS IDENTITY,
    booking_status_id int NOT NULL,
    item_id int NOT NULL,
    user_id int NOT NULL,
    booking_start TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    booking_end TIMESTAMP WITHOUT TIME ZONE NOT NULL,

    CONSTRAINT pkey_booking PRIMARY KEY(booking_id),
    CONSTRAINT fkey_booking_item FOREIGN KEY(item_id)
        REFERENCES items(item_id) ON DELETE CASCADE,
    CONSTRAINT fkey_booking_user FOREIGN KEY(user_id)
        REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT fkey_booking_booking_status FOREIGN KEY(booking_status_id)
        REFERENCES booking_statuses(booking_status_id) ON DELETE CASCADE
);

CREATE TABLE comments (
    comment_id int GENERATED BY DEFAULT AS IDENTITY,
    text varchar(250) NOT NULL,
    item_id int NOT NULL,
    user_id int NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL,

    CONSTRAINT pkey_comment PRIMARY KEY(comment_id),
    CONSTRAINT fkey_comment_item FOREIGN KEY(item_id)
        REFERENCES items(item_id) ON DELETE CASCADE,
    CONSTRAINT fkey_comment_user FOREIGN KEY(user_id)
        REFERENCES users(user_id) ON DELETE CASCADE
);