DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS items CASCADE;
DROP TABLE IF EXISTS users_items;

CREATE TABLE users (
    user_id int GENERATED BY DEFAULT AS IDENTITY,
    user_name varchar(200) NOT NULL,
    email varchar(200) NOT NULL,

    CONSTRAINT pkey_user PRIMARY KEY(user_id),
    CONSTRAINT uq_user_name UNIQUE(user_name),
    CONSTRAINT uq_user_email UNIQUE(email)
);

CREATE TABLE items (
    item_id int GENERATED BY DEFAULT AS IDENTITY,
    user_id int NOT NULL,
    item_name varchar(200) NOT NULL,
    description varchar(200) NOT NULL,
    available boolean NOT NULL,

    CONSTRAINT pkey_item PRIMARY KEY(item_id),
    CONSTRAINT fkey_item_user FOREIGN KEY(user_id)
        REFERENCES users(user_id) ON DELETE CASCADE
);

INSERT INTO users (user_name, email)
VALUES ('1', '1@email.com'),
       ('2', '2@email.com'),
       ('3', '3@email.com'),
       ('4', '4@email.com');

INSERT INTO items (user_id, item_name, description, available)
VALUES (4, '1', 'description', 'true'),
       (2, '2', 'description', 'false'),
       (4, '3', 'description', 'false');