DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS items CASCADE;
DROP TABLE IF EXISTS booking_statuses CASCADE;
DROP TABLE IF EXISTS bookings;

CREATE TABLE users (
    user_id int GENERATED BY DEFAULT AS IDENTITY,
    user_name varchar(200) NOT NULL,
    email varchar(200) NOT NULL,

    CONSTRAINT pkey_user PRIMARY KEY(user_id),
    CONSTRAINT uq_user_name UNIQUE(user_name),
    CONSTRAINT uq_user_email UNIQUE(email)
);

CREATE TABLE items (
    item_id int GENERATED BY DEFAULT AS IDENTITY,
    user_id int NOT NULL,
    item_name varchar(200) NOT NULL,
    description varchar(200) NOT NULL,
    available boolean NOT NULL,

    CONSTRAINT pkey_item PRIMARY KEY(item_id),
    CONSTRAINT fkey_item_user FOREIGN KEY(user_id)
        REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TABLE booking_statuses (
    booking_status_id int GENERATED BY DEFAULT AS IDENTITY,
    booking_status_name varchar(50) NOT NULL,

    CONSTRAINT pkey_booking_status PRIMARY KEY(booking_status_id)
);

INSERT INTO booking_statuses (booking_status_name)
VALUES ('WAITING'),
       ('APPROVED'),
       ('REJECTED'),
       ('CANCELED');

CREATE TABLE bookings (
    booking_id int GENERATED BY DEFAULT AS IDENTITY,
    booking_status_id int NOT NULL,
    item_id int NOT NULL,
    user_id int NOT NULL,
    booking_start TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    booking_end TIMESTAMP WITHOUT TIME ZONE NOT NULL,

    CONSTRAINT pkey_booking PRIMARY KEY(booking_id),
    CONSTRAINT fkey_booking_item FOREIGN KEY(item_id)
        REFERENCES items(item_id) ON DELETE CASCADE,
    CONSTRAINT fkey_booking_user FOREIGN KEY(user_id)
        REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT fkey_booking_booking_status FOREIGN KEY(booking_status_id)
        REFERENCES booking_statuses(booking_status_id) ON DELETE CASCADE
);

INSERT INTO users (user_name, email)
VALUES ('1', '1@email.com'),
       ('2', '2@email.com'),
       ('3', '3@email.com'),
       ('4', '4@email.com');

INSERT INTO items (user_id, item_name, description, available)
VALUES (4, '1', 'description', 'true'),
       (2, '2', 'description', 'false'),
       (4, '3', 'description', 'false');

INSERT INTO bookings(booking_status_id, item_id, user_id, booking_start, booking_end)
VALUES (1, 1, 1, '2020-01-01 12:00:00', '2024-01-02 12:00:00'),
       (1, 1, 3, '2024-01-01 13:00:00', '2024-01-02 13:00:00'),
       (1, 2, 1, '2024-01-01 13:00:00', '2024-01-02 13:00:00');